on:
  release:
    types: [published]

jobs:
  refresh_presentation_branch:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@6eeab5f407a63c182d82290dbf78faca18b2af3b # v2.0.1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      target_branch: main
    permissions:
      contents: write
