on:
  release:
    types: [published]

jobs:
  publish_docs:
    uses: nolte/gh-plumbing/.github/workflows/reusable-mkdocs.yaml@6eeab5f407a63c182d82290dbf78faca18b2af3b # v2.0.1
    with:
      requirements: docs/requirements.txt
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      id-token: write
      pages: write
    concurrency:
      cancel-in-progress: true
      group: "pages"
