on:
  push:
    branches: [develop]

jobs:
  update_release_draft:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-drafter.yml@6eeab5f407a63c182d82290dbf78faca18b2af3b # v2.0.1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
